### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by DCollart** [jsakamoto/CSharpProlog#1]
Hello, 

It's not really an issue but a question.

I just found your library and it seems really great :-)

Have you planned to adapt this library in .NET Core ?

Thanks you!

**Comment by jsakamoto** [comment]
@DCollart Thank you for your proposal.

I tried to add support for .NET Core, so you can install v.5.0.0.1-alpha now.

http://www.nuget.org/packages/CSProlog/5.0.0.1-alpha

```
PM> Install-Package CSProlog -Pre
```

Could you test v.5.0.0.1-alpha version?

**Comment by DCollart** [comment]
It seems to work like a charm with a .NET Core console application or a .NET standard library.
Thanks you a lot ! :-)
