### ISSUE TITLE
Should we/Can we support persistence of command history on .NET Standard edition?

### ISSUE THREAD

**Issue by jsakamoto** [jsakamoto/CSharpProlog#10]
How do we implement [this line](https://github.com/jsakamoto/CSharpProlog/commit/92f351dbf6567f70a63ea26d95b2bf69ca94e63d#diff-876d3bfc3f33b97fc96d9083354a7350R1811)?

**Comment by poolofthought** [comment]
Just to make sure I understand, you're talking about Persistent command history, yes? Both console versions (PL.Dotnet and PL.d support bash style history while the console is up. I don't think either support it from one running instance to another running instance.

**Comment by jsakamoto** [comment]
> you're talking about Persistent command history, yes?

Yes, I'm talking about "persistent" command history. I fixed the title of this issue to clear what I want to be talking.

I know that "command history" behavior works well on both console versions, by OS support. (For example  , "up" key recall the text previous entered.)

But, C#Prolog console versions has it's own command history mechanism which can call "!!" predicate.

I would like to consider well that should we continue to support this custom command history feature, or not.  
If we decide continue to support custom command history feature, next, I would like to consider that should we persist those custom command history or not.

**Comment by jsakamoto** [comment]
P.S. By the way, in fact, I don't know how to use "!!" custom command history feature...! 😆

**Comment by poolofthought** [comment]
> I know that "command history" behavior works well on both console versions, by OS support. (For example , "up" key recall the text previous entered.)

This did not work for me on ubuntu linux. The reason I added the Nuget for "Readline" and used it in a couple of places in PL.NETcore, is because the OS supported "up" key history did not work. It did in windows, but not linux. If we can figure out why it didn't work on linux then we could eliminate that whole library. It's slow (could be the way I put it to use), but it's better than no "up" history at all.

With that in mind I think we must keep the !! history. Plus it actually works very nicely and has a "sed" type feature that is pretty useful. 

Below is a sample of the program running and me using the !! history feature. Basically the ! history explodes whatever linenumber you pass it and runs it. It can explode and replace as I've also demoed below.

> P.S. By the way, in fact, I don't know how to use "!!" custom command history feature...!

Ha ha. You're missing out! I had to learn it because the "up" history didn't work in linux. Here's a sample run including using it.

```
|
| Welcome to C#Prolog MS-Windows version 4.1.0, parser 2014-04-03 21:12:01
|
| Copyright (C) 2007-2014 John Pool
|
| C#Prolog comes with ABSOLUTELY NO WARRANTY. This is free software, licenced
| under the GNU General Public License, and you are welcome to redistribute it
| under certain conditions. Enter 'license.' at the command prompt for details.

--- Enter !! for command history, help for a list of all commands

1 ?- age(ann,A).

 A = 5  more? (y/n) y

 A = 6  more? (y/n) y

false

2 ?- age(peter,B).

 B = 7  more? (y/n) y

false

3 ?- help history.

  Command history commands:
  ========================
  !!                : show numbered list of previous commands
  !                 : repeat previous command
  !<n>              : repeat command number <n>
  !/<old>/<new>/    : repeat previous command, with <old> replaced by <new>.
                     / may be any char, and the end / may be omitted.
  !<n>/<old>/<new>/ : same for command number <n>
  !c                : clear the history
  !?                : help (this text)

  History commands must not be followed by a '.'

true

4 ?- !!

 1 age(ann,A).
 2 age(peter,B).
 3 help history.

4 ?- !2
?- age(peter,B).

 B = 7  more? (y/n) y

false

5 ?- !2/age/haircolor 
?- haircolor(peter,B).

*** error: Undefined predicate: haircolor/2


6 ?-
```

**Comment by poolofthought** [comment]
I had to update the comment. The first time I quoted the wrong thing at the very top! And i did "code insertion" wrong in the sample so it came out mangled. If you're reading this all via email, you should make sure you're looking the most recent version of the last comment or it might not be clear. sorry.

**Comment by jsakamoto** [comment]
Thank you for tell me how to use "!!" history feature!

I'm not sure why linux OS/terminal based command line history feature dose not work on PL.NETCore, anyway, I agree keep !! history feature due to I understood your explain.

By the way, !! history does not persist on .NET Core app /.NET Standard 1.4 at this time.

And the other factor, if we implement persistence of !! history, it will have many tasks, I think.

Therefore, again, I think that `new CommandHistory(enablePersistence: true)` .NET Standard 1.4 edition needs to throw a `NotImplementedException` exception, at this time.

Instead, I think that PL.NETCore should instantiate the `PrologEngine` class with "false" argument at 2nd position, like this:

```csharp
e = new PrologEngine(new DosIO(), persistentCommandHistory: false);
```

if the `new CommandHistory(enablePersistence: true)` .NET Standard 1.4 edition accept this arguments as successfully, but !! history does not persist, then an user will be confused, I think.

In the future days, if we implemented persistence of !! history feature on .NET Standard edition, after that, the Main.cs of PL.NETCore can be changed `persistentCommandHistory:true`.

**Comment by poolofthought** [comment]
That all sounds good. 

At the time, I didn't realize I could just change the method call parameter to false and solve the problem. At the time I was just trying to get it running. :)

I'll see about changing that parameter and make sure everything still works.

**Comment by jsakamoto** [comment]
Thank you for your reply and pull request #19.

I'll close this issue because this is a question and I think it was resolved.

Instead, I created a new issue #20 to don't forget the task that implement persistence of command history feature on .NET Standard edition.
