### ISSUE TITLE
Add unit test for "ShowHelp"

### ISSUE THREAD

**Issue by jsakamoto** [jsakamoto/CSharpProlog#12]
We should add unit test for "ShowHelp" method before start fixing #11 .

**Comment by poolofthought** [comment]
haha... I just put a note in #11 that whoever fixes should make sure help still works afterwards. Then I thought, that should really be a unit test. Came back to issues to add the concept and you already added it here. lol.

**Comment by jsakamoto** [comment]
I'll close this issue by commit cc334a98806bf3d2ca3c149fc94c471e2e346b18.

Thanks!
