### ISSUE TITLE
GetAllSolutions only works if you pass in a file

### ISSUE THREAD

**Issue by poolofthought** [jsakamoto/CSharpProlog#16]
GetAllSolutions is supposed to be one of the methods that allows the prolog engine to be utilized from other programs. However, it only works if the program calling it actually sends a file path in as a parameter. 

The parameter is allowed to be passed in as null, and when it is null the method is probably expected to simply use the whatever the current contents of the database are at the time. Instead, when there is no file specified (aka null in the first parameter) the method returns no answers.

Good news:
I've already got this fixed and have unit tests set up for it as well (I actually found the bug after I created the test and I couldn't get it to pass). On researching it I realized there is no conditional around the reset call in this method [same for his xml counterpart method]. So it was resetting the database in preparation to read in from the file even when no file was specified.

**Comment by jsakamoto** [comment]
I'll close this issue by your great work at commit 2c2ab8ceff9449030dcd13fccf429c4ec4268293.

Thanks!
