### ISSUE TITLE
Chat and Chat80 still listed in help predicate listing

### ISSUE THREAD

**Issue by poolofthought** [jsakamoto/CSharpProlog#23]
Chat just doesn't want to go away! Related to #3.

If you type "help" you get a list of predicates. Two of those mentioned are chat/0 and chat-80*. Since we took out the rest of the chat stuff we probably need to take that out too.

**Comment by jsakamoto** [comment]
Thank you for your contributions!

I merged the pull request #24.  
This patch will be included v.6 NuGet package.
