### ISSUE TITLE
Can not add the same root fact twice by "ConsultFromString()" method.

### ISSUE THREAD

**Issue by jsakamoto** [jsakamoto/CSharpProlog#36]
@Thriliriel wrote:

> Hello.
> 
> I liked this idea a lot! I am facing a problem where i cannot add the same root fact twice. For example, if we use the readme example: 
> 
> ```csharp
> prolog.ConsultFromString("human(socrates).");`
> ```
> 
> I am not able to add another human, like, for example:
> 
> ```csharp
> prolog.ConsultFromString("human(socrates).");
> prolog.ConsultFromString("human(aristoteles).");
> ```
> 
> It raises the error: `Predicate 'human/1' is already defined in...`
> 
> Is there a way to avoid that?
> 
> Thanks!

_Originally posted by @Thriliriel in https://github.com/jsakamoto/CSharpProlog/issues/33#issuecomment-776136925_

**Comment by jsakamoto** [comment]
Hi @Thriliriel,

> I am not able to add another human, like, for example:

This behavior of the "ConsultFromString()" method looks like a bug of this library for me.

Anyway, I came up with two workarounds at this time as follows.

Workaround 1. Consult all facts at once.

```csharp
prolog.ConsultFromString("human(socrates).\r\nhuman(aristoteles).");
```

Workaround 2. Invoke query with "assert()".

```csharp
prolog.GetFirstSolution("assert(human(socrates)).");
prolog.GetFirstSolution("assert(human(aristoteles)).");
```

It will be a little bit confused us that invoking "GetFirstSolution()" means query, but it works fine.

I attached the sample source code (and the project file) to this thread.

[CSPrologApp.zip](https://github.com/jsakamoto/CSharpProlog/files/5977627/CSPrologApp.zip)

I hope this answer helps you.

**Comment by Thriliriel** [comment]
Thanks for the answer!

I was trying some alternative solutions as well and found out the first workaround you cited (the \r\n is not necessary, you can put them all together just giving a single space). But it is good to know that i can use the "assert" statement if i need to do it separately.

Thanks again =)
