### ISSUE TITLE
"help" predefined predicate dose not work

### ISSUE THREAD

**Issue by jsakamoto** [jsakamoto/CSharpProlog#5]

**Comment by poolofthought** [comment]
This will be included in my pull request. I've already fixed it. Is there a way to "claim" an issue so two people don't work on it at the same time?

**Comment by jsakamoto** [comment]
>  Is there a way to "claim" an issue so two people don't work on it at the same time?

Yes, that's right!

And, thank you for your self assign action.

I'm sorry that I did not comments about these interaction with you, but you behaved as I expected. thanks!

I received a new pull request from you, so I'll merge it after I understand it.

**Comment by jsakamoto** [comment]
This issue resolved by your commit 6670ac3cad66520a0934755dee4b629ef0bbfc55 , so I'll close this issue.

Thank you for your contribution! 👍
